export const INCREMENTCOUNTER ="INCREMENTCOUNTER"
export const DECREMENTCOUNTER ="DECREMENTCOUNTER"
 export const GET_MEDICIONS="GET_MEDICIONS"
 export const LOADING_MEDICIONS="LOADING_MEDICIONS"
 export const ERROR_MEDICION="ERROR_MEDICION"
 export const POST_MEDICIONS="POST_MEDICIONS"
 export const DELETE_MEDICIONS="DELETE_MEDICIONS"
 export const UPDATE_MEDICIONS="UPDATE_MEDICIONS"
 export const SIGNUP_USER="SIGNUP_USER"
 export const EMAIL_VEREFICATION="EMAIL_VEREFICATION"

 
 export const SET_ALERT = "SET_ALERT"
 export const RESET_ALERT = "RESET_ALERT"
